generate:
	protoc --go_out=. --go-grpc_out=. user.proto
	protoc --go_out=. --go-grpc_out=. author.proto
	protoc --go_out=. --go-grpc_out=. category.proto
	protoc --go_out=. --go-grpc_out=. book.proto
